blank_issues_enabled: false
contact_links:
  - name: Questions & Discussion
    url: https://github.com/Indelible-1/GolfBets/discussions
    about: Ask questions and discuss features in GitHub Discussions
